Repository openwallet-foundation/credo-ts, pull requests merged in 2022-06, with the labels that each got.

#557 feat: add question answer protocol
  packages/core/src/agent/Agent.ts
  packages/core/src/index.ts
  packages/core/src/modules/question-answer/QuestionAnswerEvents.ts
  packages/core/src/modules/question-answer/QuestionAnswerModule.ts
  packages/core/src/modules/question-answer/QuestionAnswerRole.ts
  packages/core/src/modules/question-answer/__tests__/QuestionAnswerService.test.ts
  packages/core/src/modules/question-answer/handlers/AnswerMessageHandler.ts
  packages/core/src/modules/question-answer/handlers/QuestionMessageHandler.ts
  packages/core/src/modules/question-answer/handlers/index.ts
  packages/core/src/modules/question-answer/index.ts
  packages/core/src/modules/question-answer/messages/AnswerMessage.ts
  packages/core/src/modules/question-answer/messages/QuestionMessage.ts
  packages/core/src/modules/question-answer/messages/index.ts
  packages/core/src/modules/question-answer/models/QuestionAnswerState.ts
  packages/core/src/modules/question-answer/models/ValidResponse.ts
  packages/core/src/modules/question-answer/models/index.ts
  packages/core/src/modules/question-answer/repository/QuestionAnswerRecord.ts
  packages/core/src/modules/question-answer/repository/QuestionAnswerRepository.ts
  packages/core/src/modules/question-answer/repository/index.ts
  packages/core/src/modules/question-answer/services/QuestionAnswerService.ts
  packages/core/src/modules/question-answer/services/index.ts
Labels: Waiting on Author

#803 fix(indy): async ledger connection issues on iOS
  packages/core/src/modules/ledger/services/IndyPoolService.ts
Labels: Waiting on Author

#882 fix(connections): allow ; to convert legacy did
  packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
  packages/core/src/modules/connections/__tests__/helpers.test.ts
  packages/core/src/modules/connections/services/helpers.ts
Labels: 0.2.0

#877 feat(credentials): add get format data method
  packages/core/src/modules/credentials/CredentialServiceOptions.ts
  packages/core/src/modules/credentials/CredentialsModule.ts
  packages/core/src/modules/credentials/CredentialsModuleOptions.ts
  packages/core/src/modules/credentials/formats/CredentialFormat.ts
  packages/core/src/modules/credentials/formats/indy/IndyCredentialFormat.ts
  packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts
  packages/core/src/modules/credentials/protocol/v1/__tests__/v1-credentials.e2e.test.ts
  packages/core/src/modules/credentials/protocol/v2/V2CredentialService.ts
  packages/core/src/modules/credentials/protocol/v2/__tests__/v2-credentials.e2e.test.ts
  packages/core/src/modules/credentials/services/CredentialService.ts
Labels: 0.2.0

#888 fix: remove usage of const enum
  .eslintrc.js
  packages/core/src/modules/connections/errors/DidExchangeProblemReportReason.ts
  packages/core/src/modules/connections/models/DidExchangeRole.ts
  packages/core/src/modules/connections/models/DidExchangeState.ts
  packages/core/src/modules/connections/models/HandshakeProtocol.ts
  packages/core/src/modules/dids/methods/peer/didPeer.ts
  packages/core/src/modules/oob/domain/OutOfBandRole.ts
  packages/core/src/modules/oob/domain/OutOfBandState.ts
  packages/core/src/storage/migration/updates/0.1-0.2/credential.ts
  packages/core/src/types.ts
Labels: 0.2.0

#830 feat: add validation to JSON transformer
  packages/core/src/agent/Agent.ts
  packages/core/src/agent/MessageReceiver.ts
  packages/core/src/agent/MessageSender.ts
  packages/core/src/agent/__tests__/AgentMessage.test.ts
  packages/core/src/decorators/ack/AckDecorator.test.ts
  packages/core/src/decorators/service/ServiceDecorator.test.ts
  packages/core/src/decorators/transport/TransportDecorator.test.ts
  packages/core/src/error/ClassValidationError.ts
  packages/core/src/error/ValidationErrorUtils.ts
  packages/core/src/error/__tests__/ValidationErrorUtils.test.ts
  packages/core/src/error/index.ts
  packages/core/src/modules/connections/__tests__/ConnectionInvitationMessage.test.ts
  packages/core/src/modules/connections/__tests__/ConnectionRequestMessage.test.ts
  packages/core/src/modules/connections/messages/ConnectionInvitationMessage.ts
  packages/core/src/modules/connections/services/ConnectionService.ts
  packages/core/src/modules/credentials/formats/indy/IndyCredentialFormatService.ts
  packages/core/src/modules/dids/domain/__tests__/DidDocument.test.ts
  packages/core/src/modules/dids/methods/web/WebDidResolver.ts
  packages/core/src/modules/oob/OutOfBandModule.ts
  packages/core/src/modules/oob/__tests__/OutOfBandInvitation.test.ts
  packages/core/src/modules/oob/__tests__/helpers.test.ts
  packages/core/src/modules/oob/messages/OutOfBandInvitation.ts
  packages/core/src/modules/proofs/__tests__/ProofRequest.test.ts
  packages/core/src/modules/proofs/models/RequestedProof.ts
  packages/core/src/utils/JsonTransformer.ts
  packages/core/src/utils/MessageValidator.ts
  packages/core/src/utils/__tests__/JsonTransformer.test.ts
  packages/core/src/utils/__tests__/MessageValidator.test.ts
  packages/core/src/utils/parseInvitation.ts
Labels: 0.2.0

#889 fix(oob): allow legacy did sov prefix
  packages/core/src/modules/oob/__tests__/OutOfBandInvitation.test.ts
  packages/core/src/modules/oob/messages/OutOfBandInvitation.ts
Labels: 0.2.0

#887 feat(credentials): find didcomm message methods
  packages/core/src/modules/credentials/CredentialsModule.ts
  packages/core/src/modules/credentials/CredentialsModuleOptions.ts
  packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts
  packages/core/src/modules/credentials/protocol/v1/__tests__/v1-credentials.e2e.test.ts
  packages/core/src/modules/credentials/protocol/v1/messages/V1ProposeCredentialMessage.ts
  packages/core/src/modules/credentials/protocol/v2/__tests__/v2-credentials.e2e.test.ts
Labels: 0.2.0

#890 chore: move to docs repo
  DEVREADME.md
  README.md
  demo/README.md
  docs/getting-started/0-agent.md
  docs/getting-started/1-transports.md
  docs/getting-started/2-connections.md
  docs/getting-started/3-routing.md
  docs/getting-started/5-credentials.md
  docs/getting-started/7-logging.md
  docs/getting-started/ledger.md
  docs/getting-started/overview.md
  docs/getting-started/proofs.md
  docs/images/The_W3C_Verifiable_Credentials_Model.png
  docs/images/dcd1.png
  docs/images/dcd2.png
  docs/images/rec_cred.png
  docs/libindy/android.md
  docs/libindy/ios.md
  docs/libindy/linux.md
  docs/libindy/macos-apple.md
  docs/libindy/macos-intel.md
  docs/libindy/windows.md
  docs/migration/0.1-to-0.2.md
  docs/migration/updating.md
  docs/postgres-plugin-setup/linux.md
  docs/postgres-plugin-setup/macos.md
  docs/postgres-plugin-setup/windows.md
  docs/setup-electron.md
  docs/setup-nodejs.md
  docs/setup-react-native.md
  samples/extension-module/README.md
Labels: 0.2.0

#904 fix(connections): fix log of object in string
  packages/core/src/modules/connections/services/ConnectionService.ts
Labels: 0.2.0

#892 fix(credentials): do not store offer attributes
  packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts
  packages/core/src/modules/credentials/protocol/v1/__tests__/V1CredentialServiceProposeOffer.test.ts
Labels: 0.2.0

#903 refactor(credentials): remove formats for version
  packages/core/src/modules/credentials/CredentialsModuleOptions.ts
Labels: 0.2.0

#909 feat(routing): add routing service
  packages/core/src/agent/Agent.ts
  packages/core/src/modules/connections/ConnectionsModule.ts
  packages/core/src/modules/connections/handlers/ConnectionRequestHandler.ts
  packages/core/src/modules/connections/handlers/DidExchangeRequestHandler.ts
  packages/core/src/modules/credentials/CredentialsModule.ts
  packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts
  packages/core/src/modules/credentials/protocol/v1/__tests__/V1CredentialServiceCred.test.ts
  packages/core/src/modules/credentials/protocol/v1/__tests__/V1CredentialServiceProposeOffer.test.ts
  packages/core/src/modules/credentials/protocol/v1/handlers/V1OfferCredentialHandler.ts
  packages/core/src/modules/credentials/protocol/v2/V2CredentialService.ts
  packages/core/src/modules/credentials/protocol/v2/__tests__/V2CredentialServiceCred.test.ts
  packages/core/src/modules/credentials/protocol/v2/__tests__/V2CredentialServiceOffer.test.ts
  packages/core/src/modules/credentials/protocol/v2/handlers/V2OfferCredentialHandler.ts
  packages/core/src/modules/ledger/__tests__/IndyPoolService.test.ts
  packages/core/src/modules/oob/OutOfBandModule.ts
  packages/core/src/modules/proofs/ProofsModule.ts
  packages/core/src/modules/proofs/handlers/RequestPresentationHandler.ts
  packages/core/src/modules/routing/RecipientModule.ts
  packages/core/src/modules/routing/RoutingEvents.ts
  packages/core/src/modules/routing/services/MediationRecipientService.ts
  packages/core/src/modules/routing/services/RoutingService.ts
  packages/core/src/modules/routing/services/__tests__/MediationRecipientService.test.ts
  packages/core/src/modules/routing/services/__tests__/RoutingService.test.ts
Labels: multitenancy
