Repository openwallet-foundation/credo-ts, pull requests merged in 2022-07, with the labels that each got.

#805 feat: present proof v2 indy
  demo/src/Faber.ts
  packages/core/src/modules/proofs/ProofResponseCoordinator.ts
  packages/core/src/modules/proofs/ProofService.ts
  packages/core/src/modules/proofs/ProofsModule.ts
  packages/core/src/modules/proofs/__tests__/V1ProofService.test.ts
  packages/core/src/modules/proofs/formats/IndyProofFormatsServiceOptions.ts
  packages/core/src/modules/proofs/formats/indy/IndyProofFormatService.ts
  packages/core/src/modules/proofs/formats/indy/IndyProofUtils.ts
  packages/core/src/modules/proofs/formats/indy/models/AttributeFilter.ts
  packages/core/src/modules/proofs/formats/indy/models/PredicateType.ts
  packages/core/src/modules/proofs/formats/indy/models/ProofAttributeInfo.ts
  packages/core/src/modules/proofs/formats/indy/models/ProofPredicateInfo.ts
  packages/core/src/modules/proofs/formats/indy/models/ProofRequest.ts
  packages/core/src/modules/proofs/formats/indy/models/RequestedAttribute.ts
  packages/core/src/modules/proofs/formats/indy/models/RequestedCredentials.ts
  packages/core/src/modules/proofs/formats/indy/models/RequestedPredicate.ts
  packages/core/src/modules/proofs/formats/indy/models/RetrievedCredentials.ts
  packages/core/src/modules/proofs/formats/indy/models/index.ts
  packages/core/src/modules/proofs/formats/models/ProofFormatServiceOptions.ts
  packages/core/src/modules/proofs/index.ts
  packages/core/src/modules/proofs/models/ProofServiceOptions.ts
  packages/core/src/modules/proofs/models/SharedOptions.ts
  packages/core/src/modules/proofs/protocol/v1/V1ProofService.ts
  packages/core/src/modules/proofs/protocol/v1/__tests__/indy-proof-presentation.test.ts
  packages/core/src/modules/proofs/protocol/v1/__tests__/indy-proof-proposal.test.ts
  packages/core/src/modules/proofs/protocol/v1/__tests__/indy-proof-request.test.ts
  packages/core/src/modules/proofs/protocol/v1/handlers/V1ProposePresentationHandler.ts
  packages/core/src/modules/proofs/protocol/v1/handlers/V1RequestPresentationHandler.ts
  packages/core/src/modules/proofs/protocol/v1/messages/V1PresentationAckMessage.ts
  packages/core/src/modules/proofs/protocol/v1/models/V1PresentationPreview.ts
  packages/core/src/modules/proofs/protocol/v1/models/index.ts
  packages/core/src/modules/proofs/protocol/v2/V2ProofService.ts
  packages/core/src/modules/proofs/protocol/v2/__tests__/indy-proof-presentation.test.ts
  packages/core/src/modules/proofs/protocol/v2/__tests__/indy-proof-proposal.test.ts
  packages/core/src/modules/proofs/protocol/v2/__tests__/indy-proof-request.test.ts
  packages/core/src/modules/proofs/protocol/v2/handlers/V2ProposePresentationHandler.ts
  packages/core/src/modules/proofs/protocol/v2/handlers/V2RequestPresentationHandler.ts
  packages/core/src/modules/proofs/protocol/v2/messages/V2PresentationAckMessage.ts
  packages/core/src/modules/proofs/protocol/v2/messages/V2PresentationMessage.ts
  packages/core/src/modules/proofs/protocol/v2/messages/V2ProposalPresentationMessage.ts
  packages/core/src/modules/proofs/protocol/v2/messages/V2RequestPresentationMessage.ts
  packages/core/src/modules/proofs/repository/PresentationExchangeRecord.ts
  packages/core/src/utils/__tests__/objectCheck.test.ts
  packages/core/src/utils/objectCheck.ts
  packages/core/tests/helpers.ts
  packages/core/tests/v1-connectionless-proofs.test.ts
  packages/core/tests/v1-indy-proofs.test.ts
  packages/core/tests/v1-proofs-auto-accept.test.ts
  packages/core/tests/v2-connectionless-proofs.test.ts
  packages/core/tests/v2-indy-proofs.test.ts
  packages/core/tests/v2-proofs-auto-accept.test.ts
Labels: breaking change

#921 feat: add agent context provider
  packages/core/src/agent/Agent.ts
  packages/core/src/agent/AgentContext.ts
  packages/core/src/agent/EnvelopeService.ts
  packages/core/src/agent/EventEmitter.ts
  packages/core/src/agent/Events.ts
  packages/core/src/agent/MessageReceiver.ts
  packages/core/src/agent/MessageSender.ts
  packages/core/src/agent/context/AgentContext.ts
  packages/core/src/agent/context/AgentContextProvider.ts
  packages/core/src/agent/context/DefaultAgentContextProvider.ts
  packages/core/src/agent/context/__tests__/DefaultAgentContextProvider.test.ts
  packages/core/src/agent/context/index.ts
  packages/core/src/agent/index.ts
  packages/core/src/agent/models/InboundMessageContext.ts
  packages/core/src/constants.ts
  packages/core/src/index.ts
  packages/core/src/modules/oob/OutOfBandModule.ts
  packages/core/src/modules/proofs/ProofResponseCoordinator.ts
  packages/core/src/modules/routing/handlers/BatchHandler.ts
  packages/core/src/modules/routing/services/MediationRecipientService.ts
  packages/core/src/modules/routing/services/__tests__/MediationRecipientService.test.ts
  packages/core/src/transport/HttpOutboundTransport.ts
  packages/core/tests/helpers.ts
  packages/node/src/transport/HttpInboundTransport.ts
  packages/node/src/transport/WsInboundTransport.ts
  tests/transport/SubjectInboundTransport.ts
  tests/transport/SubjectOutboundTransport.ts
Labels: multitenancy

#922 feat: add base agent class
  packages/core/src/agent/Agent.ts
  packages/core/src/agent/BaseAgent.ts
  packages/core/src/modules/vc/W3cCredentialService.ts
  packages/core/src/storage/migration/UpdateAssistant.ts
  packages/core/src/storage/migration/updates.ts
  packages/core/src/storage/migration/updates/0.1-0.2/connection.ts
  packages/core/src/storage/migration/updates/0.1-0.2/credential.ts
  packages/core/src/storage/migration/updates/0.1-0.2/index.ts
  packages/core/src/storage/migration/updates/0.1-0.2/mediation.ts
Labels: multitenancy

#942 feat(tenants): tenant lifecycle
  package.json
  packages/core/package.json
  packages/core/src/agent/Agent.ts
  packages/core/src/agent/BaseAgent.ts
  packages/core/src/agent/Events.ts
  packages/core/src/agent/MessageReceiver.ts
  packages/core/src/agent/context/AgentContext.ts
  packages/core/src/agent/context/AgentContextProvider.ts
  packages/core/src/agent/context/DefaultAgentContextProvider.ts
  packages/core/src/agent/context/__tests__/DefaultAgentContextProvider.test.ts
  packages/core/src/index.ts
  packages/core/src/modules/connections/services/ConnectionService.ts
  packages/core/src/modules/discover-features/DiscoverFeaturesModule.ts
  packages/core/src/modules/oob/OutOfBandModule.ts
  packages/core/src/modules/routing/RecipientModule.ts
  packages/core/src/modules/routing/services/MediationRecipientService.ts
  packages/core/src/plugins/DependencyManager.ts
  packages/core/src/plugins/index.ts
  packages/core/src/wallet/IndyWallet.ts
  packages/core/src/wallet/Wallet.ts
  packages/core/tests/mocks/MockWallet.ts
  packages/module-tenants/src/TenantAgent.ts
  packages/module-tenants/src/TenantsApi.ts
  packages/module-tenants/src/TenantsApiOptions.ts
  packages/module-tenants/src/TenantsModule.ts
  packages/module-tenants/src/__tests__/TenantAgent.test.ts
  packages/module-tenants/src/__tests__/TenantsApi.test.ts
  packages/module-tenants/src/__tests__/TenantsModule.test.ts
  packages/module-tenants/src/context/TenantAgentContextProvider.ts
  packages/module-tenants/src/context/TenantSessionCoordinator.ts
  packages/module-tenants/src/context/TenantSessionMutex.ts
  packages/module-tenants/src/context/__tests__/TenantAgentContextProvider.test.ts
  packages/module-tenants/src/context/__tests__/TenantSessionCoordinator.test.ts
  packages/module-tenants/src/context/__tests__/TenantSessionMutex.test.ts
  packages/module-tenants/src/models/TenantConfig.ts
  packages/module-tenants/src/services/TenantRecordService.ts
  packages/module-tenants/src/services/__tests__/TenantService.test.ts
  packages/module-tenants/src/services/index.ts
  packages/module-tenants/tests/tenant-sessions.e2e.test.ts
  packages/module-tenants/tests/tenants.e2e.test.ts
  yarn.lock
Labels: multitenancy

#949 feat: add dynamic suite and signing provider
  packages/core/src/crypto/BbsService.ts
  packages/core/src/crypto/__tests__/JwsService.test.ts
  packages/core/src/crypto/signing-provider/Bls12381g2SigningProvider.ts
  packages/core/src/crypto/signing-provider/SigningProvider.ts
  packages/core/src/crypto/signing-provider/SigningProviderError.ts
  packages/core/src/crypto/signing-provider/SigningProviderRegistry.ts
  packages/core/src/crypto/signing-provider/__tests__/SigningProviderRegistry.test.ts
  packages/core/src/crypto/signing-provider/index.ts
  packages/core/src/decorators/signature/SignatureDecoratorUtils.test.ts
  packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
  packages/core/src/modules/dids/__tests__/peer-did.test.ts
  packages/core/src/modules/ledger/__tests__/IndyLedgerService.test.ts
  packages/core/src/modules/ledger/__tests__/IndyPoolService.test.ts
  packages/core/src/modules/ledger/__tests__/LedgerModule.test.ts
  packages/core/src/modules/oob/__tests__/OutOfBandService.test.ts
  packages/core/src/modules/question-answer/__tests__/QuestionAnswerService.test.ts
  packages/core/src/modules/routing/services/__tests__/MediationRecipientService.test.ts
  packages/core/src/modules/vc/SignatureSuiteRegistry.ts
  packages/core/src/modules/vc/W3cCredentialService.ts
  packages/core/src/modules/vc/__tests__/W3cCredentialService.test.ts
  packages/core/src/modules/vc/module.ts
  packages/core/src/plugins/index.ts
  packages/core/src/storage/__tests__/IndyStorageService.test.ts
  packages/core/src/wallet/IndyWallet.test.ts
  packages/core/src/wallet/IndyWallet.ts
  packages/core/src/wallet/WalletModule.ts
Labels: modularization, 0.3.0

#886 feat(vc): delete w3c credential record
  packages/core/src/modules/vc/W3cCredentialService.ts
  packages/core/src/modules/vc/__tests__/W3cCredentialService.test.ts
  packages/core/src/modules/vc/models/W3cCredentialServiceOptions.ts
Labels: Waiting on Author

#935 fix(vc): change pubKey input from Buffer to Uint8Array
  packages/core/src/modules/vc/signature-suites/bbs/BbsBlsSignatureProof2020.ts
Labels: Waiting on Author

#953 feat(dids): add did registrar
  packages/core/package.json
  packages/core/src/modules/connections/DidExchangeProtocol.ts
  packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
  packages/core/src/modules/connections/services/ConnectionService.ts
  packages/core/src/modules/dids/DidsApi.ts
  packages/core/src/modules/dids/DidsModule.ts
  packages/core/src/modules/dids/DidsModuleConfig.ts
  packages/core/src/modules/dids/__tests__/DidsModule.test.ts
  packages/core/src/modules/dids/__tests__/DidsModuleConfig.test.ts
  packages/core/src/modules/dids/__tests__/dids-registrar.e2e.test.ts
  packages/core/src/modules/dids/__tests__/dids-resolver.e2e.test.ts
  packages/core/src/modules/dids/__tests__/peer-did.test.ts
  packages/core/src/modules/dids/domain/DidRegistrar.ts
  packages/core/src/modules/dids/domain/DidResolver.ts
  packages/core/src/modules/dids/domain/__tests__/DidDocument.test.ts
  packages/core/src/modules/dids/domain/index.ts
  packages/core/src/modules/dids/domain/parse.ts
  packages/core/src/modules/dids/index.ts
  packages/core/src/modules/dids/methods/index.ts
  packages/core/src/modules/dids/methods/key/KeyDidRegistrar.ts
  packages/core/src/modules/dids/methods/key/KeyDidResolver.ts
  packages/core/src/modules/dids/methods/key/__tests__/KeyDidRegistrar.test.ts
  packages/core/src/modules/dids/methods/key/__tests__/__fixtures__/didKeyz6MksLe.json
  packages/core/src/modules/dids/methods/key/index.ts
  packages/core/src/modules/dids/methods/peer/DidPeer.ts~73d296f6 (fix: always encode keys according to RFCs (#733))
  packages/core/src/modules/dids/methods/peer/PeerDidRegistrar.ts
  packages/core/src/modules/dids/methods/peer/PeerDidResolver.ts
  packages/core/src/modules/dids/methods/peer/__tests__/DidPeer.test.ts
  packages/core/src/modules/dids/methods/peer/__tests__/DidPeer.test.ts~9399a710 (feat: find existing connection based on invitation did (#698))
  packages/core/src/modules/dids/methods/peer/__tests__/PeerDidRegistrar.test.ts
  packages/core/src/modules/dids/methods/peer/__tests__/__fixtures__/didPeer0z6MksLe.json
  packages/core/src/modules/dids/methods/peer/createPeerDidDocumentFromServices.ts
  packages/core/src/modules/dids/methods/peer/index.ts
  packages/core/src/modules/dids/methods/sov/SovDidRegistrar.ts
  packages/core/src/modules/dids/methods/sov/SovDidResolver.ts
  packages/core/src/modules/dids/methods/sov/__tests__/SovDidRegistrar.test.ts
  packages/core/src/modules/dids/methods/sov/index.ts
  packages/core/src/modules/dids/methods/sov/util.ts
  packages/core/src/modules/dids/methods/web/WebDidResolver.ts
  packages/core/src/modules/dids/methods/web/index.ts
  packages/core/src/modules/dids/repository/DidRepository.ts
  packages/core/src/modules/dids/services/DidRegistrarService.ts
  packages/core/src/modules/dids/services/DidResolverService.ts
  packages/core/src/modules/dids/services/__tests__/DidRegistrarService.test.ts
  packages/core/src/modules/dids/services/__tests__/DidResolverService.test.ts
  packages/core/src/modules/dids/services/index.ts
  packages/core/src/modules/dids/types.ts
  packages/core/src/modules/ledger/services/IndyLedgerService.ts
  packages/core/src/modules/routing/services/__tests__/MediationRecipientService.test.ts
  packages/core/src/modules/vc/__tests__/W3cCredentialService.test.ts
  packages/core/src/utils/__tests__/MultibaseEncoder.test.ts
  packages/core/src/utils/__tests__/MultihashEncoder.test.ts
  packages/core/src/wallet/IndyWallet.ts
  packages/core/src/wallet/Wallet.ts
  packages/core/src/wallet/util/assertIndyWallet.ts
  packages/core/tests/__fixtures__/didKeyz6Mkqbe1.json
  packages/react-native/package.json
  yarn.lock
Labels: 0.3.0
