Repository openwallet-foundation/credo-ts, pull requests merged in 2022-05, with the labels that each got.

#726 fix: optional fields in did document
  packages/core/src/modules/dids/__tests__/__fixtures__/didKeyBls12381g1.json
  packages/core/src/modules/dids/__tests__/__fixtures__/didKeyBls12381g1g2.json
  packages/core/src/modules/dids/__tests__/__fixtures__/didKeyBls12381g2.json
  packages/core/src/modules/dids/__tests__/__fixtures__/didKeyEd25519.json
  packages/core/src/modules/dids/__tests__/__fixtures__/didKeyX25519.json
  packages/core/src/modules/dids/__tests__/__fixtures__/didPeer1zQmY.json
  packages/core/src/modules/dids/__tests__/__fixtures__/didSovR1xKJw17sUoXhejEpugMYJ.json
  packages/core/src/modules/dids/__tests__/__fixtures__/didSovWJz9mHyW9BZksioQnRsrAo.json
  packages/core/src/modules/dids/__tests__/peer-did.test.ts
  packages/core/src/modules/dids/domain/DidDocument.ts
  packages/core/src/modules/dids/domain/DidDocumentBuilder.ts
  packages/core/src/modules/dids/domain/__tests__/DidDocument.test.ts
  packages/core/src/modules/dids/domain/service/ServiceTransformer.ts
  packages/core/src/modules/dids/domain/verificationMethod/VerificationMethodTransformer.ts
  packages/core/src/modules/dids/index.ts
  packages/core/src/modules/dids/methods/peer/DidPeer.ts
  packages/core/src/modules/dids/methods/peer/PeerDidResolver.ts
  packages/core/src/modules/dids/methods/peer/__tests__/DidPeer.test.ts
  packages/core/src/modules/dids/methods/peer/__tests__/__fixtures__/didPeer1zQmR.json
  packages/core/src/modules/dids/methods/peer/__tests__/__fixtures__/didPeer1zQmZ.json
  packages/core/src/modules/dids/methods/peer/__tests__/didPeer.test.ts
  packages/core/src/modules/dids/methods/peer/__tests__/peerDidNumAlgo0.test.ts
  packages/core/src/modules/dids/methods/peer/__tests__/peerDidNumAlgo1.test.ts
  packages/core/src/modules/dids/methods/peer/didPeer.ts
  packages/core/src/modules/dids/methods/peer/peerDidNumAlgo0.ts
  packages/core/src/modules/dids/methods/peer/peerDidNumAlgo1.ts
  packages/core/src/modules/dids/methods/peer/peerDidNumAlgo2.ts
  packages/core/src/utils/transformers.ts
  packages/core/tests/dids.test.ts
Labels: OOB - DidExchange

#770 fix: delete credentials
  packages/core/src/modules/credentials/CredentialsModule.ts
  packages/core/src/modules/credentials/__tests__/V1CredentialService.cred.test.ts
  packages/core/src/modules/credentials/__tests__/V2CredentialService.cred.test.ts
  packages/core/src/modules/credentials/formats/CredentialFormatService.ts
  packages/core/src/modules/credentials/formats/indy/IndyCredentialFormatService.ts
  packages/core/src/modules/credentials/protocol/v2/__tests__/v2credentials.propose-offer.test.ts
  packages/core/src/modules/credentials/repository/CredentialExchangeRecord.ts
  packages/core/src/modules/credentials/services/CredentialService.ts
Labels: Waiting on Author

#777 fix: add oob state and role check
  packages/core/src/modules/connections/DidExchangeProtocol.ts
Labels: OOB - DidExchange

#779 docs: fix demo for oob
  demo/src/Alice.ts
  demo/src/AliceInquirer.ts
Labels: OOB - DidExchange

#769 fix: miscellaneous issue credential v2 fixes
  packages/core/src/modules/credentials/CredentialResponseCoordinator.ts
  packages/core/src/modules/credentials/CredentialServiceOptions.ts
  packages/core/src/modules/credentials/CredentialsModule.ts
  packages/core/src/modules/credentials/CredentialsModuleOptions.ts
  packages/core/src/modules/credentials/__tests__/V1CredentialService.cred.test.ts
  packages/core/src/modules/credentials/__tests__/V2CredentialService.cred.test.ts
  packages/core/src/modules/credentials/composeAutoAccept.ts
  packages/core/src/modules/credentials/formats/indy/IndyCredentialFormatService.ts
  packages/core/src/modules/credentials/formats/models/CredentialFormatServiceOptions.ts
  packages/core/src/modules/credentials/index.ts
  packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts
  packages/core/src/modules/credentials/protocol/v1/handlers/V1OfferCredentialHandler.ts
  packages/core/src/modules/credentials/protocol/v2/CredentialMessageBuilder.ts
  packages/core/src/modules/credentials/protocol/v2/V2CredentialService.ts
  packages/core/src/modules/credentials/protocol/v2/__tests__/v1credentials-auto-accept.test.ts
  packages/core/src/modules/credentials/protocol/v2/__tests__/v2credentials-auto-accept.test.ts
  packages/core/src/modules/credentials/protocol/v2/__tests__/v2credentials.propose-offer.test.ts
  packages/core/src/modules/credentials/protocol/v2/handlers/V2OfferCredentialHandler.ts
  packages/core/src/modules/credentials/protocol/v2/messages/V2IssueCredentialMessage.ts
  packages/core/src/modules/credentials/protocol/v2/messages/V2OfferCredentialMessage.ts
  packages/core/src/modules/credentials/protocol/v2/messages/V2RequestCredentialMessage.ts
  packages/core/src/modules/credentials/repository/CredentialExchangeRecord.ts
  packages/core/src/modules/credentials/services/CredentialService.ts
Labels: Waiting on Author, ICv2

#782 fix: remove unqualified did from out of band record
  packages/core/src/agent/Agent.ts
  packages/core/src/agent/MessageSender.ts
  packages/core/src/agent/__tests__/MessageSender.test.ts
  packages/core/src/modules/connections/ConnectionsModule.ts
  packages/core/src/modules/connections/DidExchangeProtocol.ts
  packages/core/src/modules/connections/__tests__/ConnectionService.test.ts
  packages/core/src/modules/connections/handlers/ConnectionRequestHandler.ts
  packages/core/src/modules/connections/handlers/ConnectionResponseHandler.ts
  packages/core/src/modules/connections/handlers/DidExchangeRequestHandler.ts
  packages/core/src/modules/connections/handlers/DidExchangeResponseHandler.ts
  packages/core/src/modules/connections/models/did/authentication/index.ts
  packages/core/src/modules/connections/repository/ConnectionRecord.ts
  packages/core/src/modules/connections/services/ConnectionService.ts
  packages/core/src/modules/credentials/CredentialsModule.ts
  packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts
  packages/core/src/modules/credentials/protocol/v1/handlers/V1OfferCredentialHandler.ts
  packages/core/src/modules/credentials/protocol/v2/V2CredentialService.ts
  packages/core/src/modules/credentials/protocol/v2/handlers/V2OfferCredentialHandler.ts
  packages/core/src/modules/oob/OutOfBandModule.ts
  packages/core/src/modules/oob/repository/OutOfBandRecord.ts
  packages/core/src/modules/proofs/ProofsModule.ts
  packages/core/src/modules/proofs/handlers/RequestPresentationHandler.ts
  packages/core/src/modules/routing/services/MediationRecipientService.ts
  packages/core/src/storage/migration/__tests__/__snapshots__/0.1.test.ts.snap
  packages/core/src/storage/migration/updates/0.1-0.2/__tests__/connection.test.ts
  packages/core/src/storage/migration/updates/0.1-0.2/connection.ts
  packages/core/src/utils/__tests__/JsonTransformer.test.ts
  packages/core/src/utils/did.ts
  packages/core/tests/generic-records.test.ts
  packages/core/tests/helpers.ts
  packages/core/tests/oob-mediation-provision.test.ts
  packages/core/tests/oob-mediation.test.ts
  packages/core/tests/oob.test.ts
Labels: OOB - DidExchange

#772 refactor: do not add ~service in createOOBOffer method
  packages/core/src/modules/credentials/CredentialsModule.ts
  packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts
  packages/core/src/modules/credentials/protocol/v2/V2CredentialService.ts
  packages/core/src/modules/credentials/protocol/v2/__tests__/v1connectionless-credentials.test.ts
  packages/core/src/modules/credentials/protocol/v2/__tests__/v2connectionless-credentials.test.ts
  packages/core/src/modules/credentials/services/CredentialService.ts
  packages/core/src/modules/oob/OutOfBandModule.ts
  packages/core/src/storage/__tests__/DidCommMessageRepository.test.ts
  packages/core/src/storage/didcomm/DidCommMessageRepository.ts
  packages/core/tests/helpers.ts
  packages/core/tests/oob.test.ts
Labels: OOB - DidExchange

#767 refactor: delete credentials by default when deleting exchange
  packages/core/src/modules/credentials/__tests__/V1CredentialServiceCred.test.ts
  packages/core/src/modules/credentials/__tests__/V2CredentialServiceCred.test.ts
  packages/core/src/modules/credentials/services/CredentialService.ts
Labels: Waiting on Author
